name: GBmu
description: Game Boy for browser
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: ^0.10.0
  ft:
    path: ./ft
  emulator:
    path: ./emulator
transformers:
- $dart2js:
    checked: true
    commandLineOptions: [--enable-diagnostic-colors, --show-package-warnings, --assert-message]
    # analyze-all: true
    # minify: true
