name: GBmu
description: GameBoy for browser
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: ^0.10.0
  ft:
    path: ./ft
  emulator:
    path: ./emulator
  component_system:
    path: ./component_system
transformers:
- $dart2js:
    $exclude: test
    checked: true
    # minify: true
    sourceMaps: true
    verbose: true
    environment:
      FTLOG: 'true'
    commandLineOptions: [--enable-diagnostic-colors, --show-package-warnings, --assert-message]
    # analyze-all: true
