name: test
description: test test
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  browser: ^0.10.0
transformers:
- $dart2js:
    checked: true
    # analyze-all: true
    # minify: true
    # environment:
      # FTLOG: 'true'
    commandLineOptions: [--enable-diagnostic-colors, --show-package-warnings, --assert-message]
