name: component_system
description: Component system part of the DOM
version: 0.0.1
environment:
  sdk: '>=1.13.0 <2.0.0'
dependencies:
  ft:
    path: ../ft
  emulator:
    path: ../emulator
transformers:
- $dart2js:
    checked: true
    # minify: true
    commandLineOptions: [--enable-diagnostic-colors, --show-package-warnings, --assert-message]
    # analyze-all: true
